trigger:
  branches:
    include:
      - heimdalltesting  # Replace with your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: MavenAuthenticate@0
  displayName: 'Maven Authenticate'
  inputs:
    artifactsFeeds: 'mavenRepo'
    mavenServiceConnections: 'Maven package Java project Web App to linux with Azure'  # Replace with your Maven service connection name

- task: Maven@3
  displayName: 'Maven Package'
  inputs:
    mavenPomFile: 'MyWebApp/pom.xml'  # Replace with the path to your pom.xml file
    options: '-DskipTests'

- task: CopyFiles@2
  displayName: 'Copy WAR file'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/target'
    Contents: '**/*.war'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'war'
