trigger:
  branches:
    include:
      - heimdalltesting  # Replace with your branch name

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Your-Azure-Subscription'  # Replace with the name of your Azure service connection
  appName: 'heimdall-core'  # Replace with your Azure Web App name
  resourceGroup: 'Your-Resource-Group'  # Replace with your Azure resource group name
  containerRegistry: 'Your-Container-Registry'  # Replace with your Azure Container Registry name

stages:
  - stage: Build
    displayName: 'Build Java Project'
    jobs:
      - job: Build
        displayName: 'Build'
        steps:
          - task: UseJavaVersion@1
            inputs:
              versionSpec: '11'

          - task: MavenAuthenticate@0
            displayName: 'Maven Authenticate'
            inputs:
              artifactsFeeds: 'mavenRepo'
              mavenServiceConnections: '$(azureSubscription)'

          - task: Maven@3
            displayName: 'Maven Package'
            inputs:
              mavenPomFile: 'pom.xml'
              options: '-DskipTests'

          - task: CopyFiles@2
            displayName: 'Copy WAR file'
            inputs:
              SourceFolder: '$(Pipeline.Workspace)/target'
              Contents: '**/*.war'
              TargetFolder: '$(Pipeline.Workspace)/publish'

  - stage: Deploy
    displayName: 'Deploy to Azure Web App'
    dependsOn: Build
    jobs:
      - deployment: Deploy
        displayName: 'Deploy'
        environment:
          name: 'staging'
          resourceType: 'VirtualMachine'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: 'Azure Web App Deploy'
                  inputs:
                    azureSubscription: '$(azureSubscription)'
                    appType: 'webAppLinux'
                    appName: '$(appName)'
                    package: '$(Pipeline.Workspace)/publish/*.war'
                    resourceGroupName: '$(resourceGroup)'
                    runtimeStack: 'TOMCAT|9.0-jre11'
                    containerRegistry: '$(containerRegistry)'
                    containerImageTag: '$(Build.BuildId)'
