name: Azure Web App Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Test1
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Adjust as needed

      - name: Build with Gradle
        run: ./gradlew build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: your-webapp-name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Add this secret in your repository settings

